# .circleci/config.yml

version: 2
jobs:
  build-and-test:
    macos:
      xcode: "11.2.1"
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - run:
          name: install node@12.0.0
          command: |
            brew install node@12
            brew unlink node
            brew link --force --overwrite node@12
      - restore_cache:
          key: yarn-v8-{{ checksum "yarn.lock" }}-{{ arch }}
      - restore_cache:
          key: node-v8-{{ checksum "package.json" }}-{{ arch }}
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          key: yarn-v8-{{ checksum "yarn.lock" }}-{{ arch }}
          paths:
            - ~/.cache/yarn
      - save_cache:
          key: node-v8-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules
      - restore_cache:
          key: bundle-v8-{{ checksum "Gemfile.lock" }}-{{ arch }}
      - run:
          name: Bundle install
          command: bundle check || bundle install
      - save_cache:
          key: bundle-v8-{{ checksum "Gemfile.lock" }}-{{ arch }}
          paths:
            - vendor/bundle
      # - run:
      #     name: Test suites
      #     command: yarn test
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan

  beta:
    macos:
      xcode: "11.2.1"
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: ios beta
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      # - run:
      #     name: install node@12.0.0
      #     command: |
      #       brew install node@12
      #       brew unlink node
      #       brew link --force --overwrite node@12
      - restore_cache:
          key: yarn-v8-{{ checksum "yarn.lock" }}-{{ arch }}
      - restore_cache:
          key: node-v8-{{ checksum "package.json" }}-{{ arch }}
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          key: yarn-v8-{{ checksum "yarn.lock" }}-{{ arch }}
          paths:
            - ~/.cache/yarn
      - save_cache:
          key: node-v8-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules
      - run:
          name: "Install React Native dependencies"
          command: HOMEBREW_NO_AUTO_UPDATE=1 brew install watchman
      - restore_cache:
          key: bundle-v8-{{ checksum "Gemfile.lock" }}-{{ arch }}
      - run: bundle install
      - save_cache:
          key: bundle-g6-{{ checksum "Gemfile.lock" }}-{{ arch }}
          paths:
            - vendor/bundle
      - restore_cache:
          key: pods-v8-{{ checksum "ios/Podfile.lock" }}
      - run:
          name: Install CocoaPods
          command: cd ios ; pod install ;
      - save_cache:
          key: pods-v8-{{ checksum "ios/Podfile.lock" }}
          paths:
            - ./Pods
      - run:
          name: Install command line tool
          command: |
            npm install -g react-native-cli
            npm install -g react-native-version
      - run:
          name: Build entry file
          command: react-native bundle --entry-file index.js --platform ios --dev false --bundle-output ios/main.jsbundle --assets-dest ios
      - run:
          name: Fastlane
          command: bundle exec fastlane $FASTLANE_LANE
      - deploy:
          command: |
            git config credential.helper 'cache --timeout=120'
            git remote set-url origin https://seasons:219f55b3ad3f2c7bc2797ed56fe61124b31e31ea@github.com/seasons/harvest.git

            # Push quietly to prevent showing the token in log
            git add .; git commit -m "Increment build number [ci skip]"; git push -q --set-upstream origin release;
      - store_artifacts:
          path: output/Seasons.ipa

workflows:
  version: 2
  beta-release:
    jobs:
      # - build-and-test
      - beta:
          filters:
            branches:
              only: release
          # requires:
          #   - build-and-test
