# .circleci/config.yml

version: 2
jobs:
  build-and-test:
    macos:
      xcode: "10.3.0"
    working_directory: /Users/distiller/project
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install
      - restore_cache:
          key: 1-gems-{{ checksum "Gemfile.lock" }}
      - run:
          name: Bundle install
          command: bundle check || bundle install
      - save_cache:
          key: 1-gems-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Test suites
          command: yarn test
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan

  beta:
    macos:
      xcode: "10.3.0"
    working_directory: /Users/distiller/project
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: ios beta
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: "Install React Native dependencies"
          command: |
            brew update
            brew install watchman
      - run: bundle install
      - run:
          name: Install CocoaPods
          command: cd ios ; pod install ;
      - run:
          name: Fastlane
          command: bundle exec fastlane $FASTLANE_LANE
      - store_artifacts:
          path: output/Seasons.ipa

workflows:
  version: 2
  beta-release:
    jobs:
      - build-and-test
      - beta:
          filters:
            branches:
              only: release
          requires:
            - build-and-test
