# .circleci/config.yml

version: 2
jobs:
  build-and-test:
    macos:
      xcode: "11.3.1"
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - run:
          name: install node@13.7.0
          command: |
            set +e         
            touch $BASH_ENV    
            curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.5/install.sh | bash
            echo 'export NVM_DIR="$HOME/.nvm"' >> $BASH_ENV
            echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> $BASH_ENV
            echo nvm install 13.7.0 >> $BASH_ENV
            echo nvm alias default 13.7.0 >> $BASH_ENV
      - run:
          name: verify node version
          command: node --version
      - restore_cache:
          key: yarn-v4-{{ checksum "yarn.lock" }}-{{ arch }}
      - restore_cache:
          key: node-v4-{{ checksum "package.json" }}-{{ arch }}
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          key: yarn-v4-{{ checksum "yarn.lock" }}-{{ arch }}
          paths:
            - ~/.cache/yarn
      - save_cache:
          key: node-v4-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules
      - restore_cache:
          key: bundle-v4-{{ checksum "Gemfile.lock" }}-{{ arch }}
      - run:
          name: Bundle install
          command: bundle check || bundle install
      - save_cache:
          key: bundle-v4-{{ checksum "Gemfile.lock" }}-{{ arch }}
          paths:
            - vendor/bundle
      # - run:
      #     name: Test suites
      #     command: yarn test
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan

  beta:
    macos:
      xcode: "11.3.1"
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: ios beta
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - restore_cache:
          key: yarn-v4-{{ checksum "yarn.lock" }}-{{ arch }}
      - restore_cache:
          key: node-v4-{{ checksum "package.json" }}-{{ arch }}
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          key: yarn-v4-{{ checksum "yarn.lock" }}-{{ arch }}
          paths:
            - ~/.cache/yarn
      - save_cache:
          key: node-v4-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules
      - run:
          name: "Install React Native dependencies"
          command: HOMEBREW_NO_AUTO_UPDATE=1 brew install watchman
      - restore_cache:
          key: bundle-v4-{{ checksum "Gemfile.lock" }}-{{ arch }}
      - run: bundle install
      - save_cache:
          key: bundle-v4-{{ checksum "Gemfile.lock" }}-{{ arch }}
          paths:
            - vendor/bundle
      - restore_cache:
          key: pods-v4-{{ checksum "ios/Podfile.lock" }}
      - run:
          name: Install CocoaPods
          command: cd ios ; pod install ;
      - save_cache:
          key: pods-v4-{{ checksum "ios/Podfile.lock" }}
          paths:
            - ./Pods
      - run:
          name: Install command line tool
          command: |
            npm install -g react-native-cli
            npm install -g react-native-version
      - run:
          name: Fastlane
          command: bundle exec fastlane $FASTLANE_LANE
      - store_artifacts:
          path: output/Seasons.ipa

workflows:
  version: 2
  beta-release:
    jobs:
      - build-and-test
      - beta:
          filters:
            branches:
              only: release
          requires:
            - build-and-test
