# .circleci/config.yml

version: 2
jobs:
  build-and-test:
    macos:
      xcode: "11.3.1"
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - restore_cache:
          key: yarn-v5-{{ checksum "yarn.lock" }}-{{ arch }}
      - restore_cache:
          key: node-v5-{{ checksum "package.json" }}-{{ arch }}
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          key: yarn-v5-{{ checksum "yarn.lock" }}-{{ arch }}
          paths:
            - ~/.cache/yarn
      - save_cache:
          key: node-v5-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules
      - restore_cache:
          key: bundle-v5-{{ checksum "Gemfile.lock" }}-{{ arch }}
      - run:
          name: Bundle install
          command: bundle check || bundle install
      - save_cache:
          key: bundle-v5-{{ checksum "Gemfile.lock" }}-{{ arch }}
          paths:
            - vendor/bundle
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan

  beta:
    macos:
      xcode: "11.3.1"
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: ios beta
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - restore_cache:
          key: yarn-v5-{{ checksum "yarn.lock" }}-{{ arch }}
      - restore_cache:
          key: node-v5-{{ checksum "package.json" }}-{{ arch }}
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          key: yarn-v5-{{ checksum "yarn.lock" }}-{{ arch }}
          paths:
            - ~/.cache/yarn
      - save_cache:
          key: node-v5-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules
      - run:
          name: "Install React Native dependencies"
          command: HOMEBREW_NO_AUTO_UPDATE=1 brew install watchman
      - restore_cache:
          key: bundle-v5-{{ checksum "Gemfile.lock" }}-{{ arch }}
      - run: bundle install
      - save_cache:
          key: bundle-g5-{{ checksum "Gemfile.lock" }}-{{ arch }}
          paths:
            - vendor/bundle
      - restore_cache:
          key: pods-v5-{{ checksum "ios/Podfile.lock" }}
      - run:
          name: Install CocoaPods
          command: cd ios ; pod install ;
      - save_cache:
          key: pods-v5-{{ checksum "ios/Podfile.lock" }}
          paths:
            - ./Pods
      - run:
          name: Install command line tool
          command: |
            npm install -g react-native-cli
            npm install -g react-native-version
      # TODO: Fix this. Somewhere in the git history, we ran into an issue with the casing of the file src/Utils.
      # More specifically, we renamed from src/Utils -> src/utils but we're running into issues getting this change
      # to propogate in the CircleCI environment.
      - run:
          name: manual fix
          command: mv src/Utils src/utils
      - run:
          name: Build entry file
          command: react-native bundle --entry-file index.js --platform ios --dev false --bundle-output ios/main.jsbundle --assets-dest ios --verbose
      - run:
          name: Fastlane
          command: bundle exec fastlane $FASTLANE_LANE
      - store_artifacts:
          path: output/Seasons.ipa

workflows:
  version: 2
  beta-release:
    jobs:
      - build-and-test
      - beta:
          filters:
            branches:
              only: release-2
          requires:
            - build-and-test
