platform :ios do  
    before_all do
        setup_circle_ci
    end  
    desc 'Fetch certificates and provisioning profiles'
    lane :certificates do
        match(app_identifier: 'com.seasons.Seasons', username: 'dev@seasons.nyc', type: "appstore")
    end

    desc 'Fetch certificates. Build the iOS application.'
    lane :build do
        certificates
        increment_build_number(xcodeproj: './ios/seasons.xcodeproj')
        commit_version_bump(
            message: "Increment Version [ci skip]",
            xcodeproj: "ios/seasons.xcodeproj"
        )
        clear_derived_data
        gym(scheme: 'seasons', 
            workspace: './ios/seasons.xcworkspace', export_method: 'app-store')
    end

    desc 'Fetch certificates, build and upload to App Center.'
    lane :beta do
        build
        changelog_from_git_commits
        upload_to_testflight(
            skip_waiting_for_build_processing: true
        )
    end
end
  