platform :ios do  
    before_all do
        setup_circle_ci
    end  
    desc 'Fetch certificates and provisioning profiles'
    lane :certificates do
        match(app_identifier: 'com.seasons.Seasons', username: 'dev@seasons.nyc', type: "appstore")
    end

    desc 'Fetch certificates. Build the iOS application.'
    lane :build do
        certificates
        increment_build_number(xcodeproj: './ios/seasons.xcodeproj')
        commit_version_bump(
            message: "[ci skip] Increment version",
            xcodeproj: "ios/seasons.xcodeproj"
        )
        gym(scheme: 'seasons', 
            workspace: './ios/seasons.xcworkspace', export_method: 'app-store')
        clean_build_artifacts
        push_to_git_remote(remote: 'origin', local_branch: 'release', remote_branch: 'release')
    end

    desc 'Fetch certificates, build and upload to App Center.'
    lane :beta do
        build
        changelog_from_git_commits
        upload_to_testflight(
            skip_waiting_for_build_processing: true
        )
    end
end
  
